INSERT INTO companies ("name", "apiKey") VALUES ('Driven', 'zadKLNx.DzvOVjQH01TumGl2urPjPQSxUbf67vs0');
INSERT INTO companies ("name", "apiKey") VALUES ('Ifood', 'ifood.DzvOVjQH01TumGl2urPjPQSxUbf67vs0');
INSERT INTO employees ("fullName", "cpf", "email", "companyId") VALUES ('Fulano Rubens da Silva', '47100935741', 'fulano.silva@gmail.com', 1);
INSERT INTO employees ("fullName", "cpf", "email", "companyId") VALUES ('Ciclana Maria Madeira', '08434681895', 'ciclaninha@gmail.com', 1);
INSERT INTO employees ("fullName", "cpf", "email", "companyId") VALUES ('Beltrano José da Silva', '98100935741', 'beltrano.silva@gmail.com', 2);
INSERT INTO businesses ("name", "type") VALUES ('Responde Aí', 'education');
INSERT INTO businesses ("name", "type") VALUES ('Extra', 'groceries');
INSERT INTO businesses ("name", "type") VALUES ('Driven Eats', 'restaurants');
INSERT INTO businesses ("name", "type") VALUES ('Uber', 'transport');
INSERT INTO businesses ("name", "type") VALUES ('Unimed', 'health');